site_name: "iLibrary Documentation"
site_url: https://legnerbeer.github.io/iLibrary/

theme:
  name: mkdocs  # This is the built-in default theme

nav:
  - Home: index.md
  - API Reference:
      - Library: iLibrary/src/Library.md
      - User: iLibrary/src/User.md
      - Save: iLibrary/src/saveLibrary.md
      - Info (Library): iLibrary/src/getInfoForLibrary.md
      - Info (User): iLibrary/src/getUserInfoForUser.md
      - Message: iLibrary/src/sendMSG.md
