site_name: "iLibrary Documentation"
site_url: https://legnerbeer.github.io/iLibrary/  # <--- MUST HAVE THE TRAILING SLASH
use_directory_urls: false

theme:
  name: material  # You already have this installed via your logs!


nav:
  - Home: index.md
  - API Reference:
      - Library: iLibrary/src/Library.md
      - User: iLibrary/src/User.md
      - Save: iLibrary/src/saveLibrary.md
      # Add the others here following the same pattern
