name: website

on:
  push:
    branches: ["main", "master", "Developer"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- STEP 1: RUN YOUR PYTHON SCRIPT ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pdoc mkdocs

      - name: Generate API Reference
        run: python docs/makedoc.py

      # --- STEP 2: LINK TO MKDOCS BUILD ---
      - name: Build Static Website
        run: mkdocs build

      # --- STEP 3: LINK TO THE WORKING DEPLOYMENT ---
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site  # This folder was created by Step 2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4